// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.thinkgem.jeesite.modules.clw.entity.listapp;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;

@Servant
public interface ListPrx {

	public java.util.List<Car> list(java.util.List<Car> coordinates);

	public java.util.List<Car> list(java.util.List<Car> coordinates, @TarsContext java.util.Map<String, String> ctx);

	public void async_list(@TarsCallback ListPrxCallback callback, java.util.List<Car> coordinates);

	public void async_list(@TarsCallback ListPrxCallback callback, java.util.List<Car> coordinates, @TarsContext java.util.Map<String, String> ctx);
}
