// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.thinkgem.jeesite.modules.clw.entity.coordinateapp;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface CoordinatePrx {

	public java.util.List<String> coordinate(String syskey, String carids, java.util.List<String> coordinates);

	public java.util.List<String> coordinate(String syskey, String carids, java.util.List<String> coordinates, @TarsContext java.util.Map<String, String> ctx);

	public void async_coordinate(@TarsCallback CoordinatePrxCallback callback, String syskey, String carids, java.util.List<String> coordinates);

	public void async_coordinate(@TarsCallback CoordinatePrxCallback callback, String syskey, String carids, java.util.List<String> coordinates, @TarsContext java.util.Map<String, String> ctx);
}
