// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.thinkgem.jeesite.modules.clw.entity.clapp;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface ClPrx {

	public java.util.List<Car> cl(String id, java.util.List<Car> carlists);

	public java.util.List<Car> cl(String id, java.util.List<Car> carlists, @TarsContext java.util.Map<String, String> ctx);

	public void async_cl(@TarsCallback ClPrxCallback callback, String id, java.util.List<Car> carlists);

	public void async_cl(@TarsCallback ClPrxCallback callback, String id, java.util.List<Car> carlists, @TarsContext java.util.Map<String, String> ctx);
}
