// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.thinkgem.jeesite.modules.clw.entity.carposition;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class CarPositionPrxCallback extends TarsAbstractCallback {

	public abstract void callback_getCarPosition(String ret);

}
