// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.thinkgem.jeesite.modules.clw.entity.carposition;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class CarPosition {

	@TarsStructProperty(order = 0, isRequire = true)
	public String lng = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public String lat = "";

	public String getLng() {
		return lng;
	}

	public void setLng(String lng) {
		this.lng = lng;
	}

	public String getLat() {
		return lat;
	}

	public void setLat(String lat) {
		this.lat = lat;
	}

	public CarPosition() {
	}

	public CarPosition(String lng, String lat) {
		this.lng = lng;
		this.lat = lat;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(lng);
		result = prime * result + TarsUtil.hashCode(lat);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof CarPosition)) {
			return false;
		}
		CarPosition other = (CarPosition) obj;
		return (
			TarsUtil.equals(lng, other.lng) &&
			TarsUtil.equals(lat, other.lat) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != lng) {
			_os.write(lng, 0);
		}
		if (null != lat) {
			_os.write(lat, 1);
		}
	}

	public void readFrom(TarsInputStream _is) {
		this.lng = _is.read(lng, 0, true);
		this.lat = _is.read(lat, 1, true);
	}

}
